const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const userSchema = new Schema({
    name: String,
    address: String,
    state: String,
    city: String,
    pin: String,
    email: String,
    contact: String,
    formedAnyCompany: String,
    incorporationNumber: String,
    certificateNo: String,
    age: String,
    founder: String,
    state: String,
    description: String,
    sector: Array,
    femaleFoundersNo: String,
    founders20: String,
    founders25: String,
    founder30: String,
    founder40: String,
    founderMoreThan40: String,
    founderHS: String,
    founderBach: String,
    founderMaster: String,
    founderMBA: String,
    founderOther: String,
    founderScience: String,
    founderArts: String,
    founderCommerce: String,
    founderEng: String,
    founderMed: String,
    founderMarketing: String,
    founderIT: String,
    founderLaw: String,
    founderOthers: String,
    founderProf: String,
    founderBusiness: String,
    founderStudent: String,
    founderOthers: String,
    patents: String,
    helped: Array,
    stage: String,
    under: String,
    incubatorName: String,
    acceleratorName: String,
    investorName: String,
    targetMarket: Array,
    targetCustomer: Array,
    technology: Array,
    funds: Array,
    employees: String,
    challanges: Array,
    userId: {
        type: Schema.Types.ObjectId,
        ref: 'Admin',
        required: true
    }
}, { timestamps: true });

module.exports = mongoose.model('StartUp', userSchema);